### ISSUE TITLE
Crash upon Load

### ISSUE THREAD

**Issue by dabriian** [ZeroChaotic/XRenPy#22]
When loading an existing RenPy project, XRenPy crashes

**Comment by ZeroChaotic** [comment]
> When loading an existing RenPy project, XRenPy crashes

Please provide more information about this issue. Which project, how complex is it?

**Comment by arlj11** [comment]
I have the same problem. What would you like order to diagnose the problem?

**Comment by ZeroChaotic** [comment]
> I have the same problem. What would you like in order to diagnose the problem?

If you created the project with XRen'Py earlier, it has to be fine.
If not, it might crash in cases of use of unsupported code.
Please provide me the code you used to load into the program so I can investigate the problem.

**Comment by cooperdk** [comment]
I have the same problem, although, when I open a renpy project, the editor just hangs.

The project is not created with the editor, but that really shouldn't be a requirement either. If it is, the editor is basically useless since many use templates to get started.

**Comment by ZeroChaotic** [comment]
> I have the same problem, although, when I open a renpy project, the editor just hangs.
> 
> The project is not created with the editor, but that really shouldn't be a requirement either. If it is, the editor is basically useless since many use templates to get started.

Please provide project files so I can investigate the issue.
All the media files can be replaced by small placeholders or deleted, but the script, options, screens and gui files have to remain the same so I can find out why does the editor hang.

**Comment by cooperdk** [comment]
Default files just saved and then reopened.

 

Fra: ZeroChaotic ***@***.***> 
Sendt: 5. maj 2021 18:20
Til: ZeroChaotic/XRenPy ***@***.***>
Cc: cooperdk ***@***.***>; Comment ***@***.***>
Emne: Re: [ZeroChaotic/XRenPy] Crash upon Load (#22)

 

I have the same problem, although, when I open a renpy project, the editor just hangs.

The project is not created with the editor, but that really shouldn't be a requirement either. If it is, the editor is basically useless since many use templates to get started.

Please provide project files so I can investigate the issue.
All the media files can be replaced by small placeholders or deleted, but the script, options, screens and gui files have to remain the same so I can find out why does the editor hang.

**Comment by ZeroChaotic** [comment]
> Default files just saved and then reopened. 
Please check latest version. It has to have that fixed.
